//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.27 at 11:17:55 PM EET 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_surfacechemistry._5;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_surfacechemistry._5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionFunctionalisationFunctionalGroupEntryKeyResult_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-SurfaceChemistry/5.0", "KeyResult");
    private final static QName _ENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionFunctionalisationFunctionalGroupEntryStDev_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-SurfaceChemistry/5.0", "StDev");
    private final static QName _ENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataUsedForMSDS_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-SurfaceChemistry/5.0", "UsedForMSDS");
    private final static QName _ENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataUsedForClassification_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-SurfaceChemistry/5.0", "UsedForClassification");
    private final static QName _ENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataRobustStudy_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-SurfaceChemistry/5.0", "RobustStudy");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_surfacechemistry._5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry createENDPOINTSTUDYRECORDSurfaceChemistry() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.OverallRemarksAttachments createENDPOINTSTUDYRECORDSurfaceChemistryOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDSurfaceChemistryOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionFunctionalisation() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionFunctionalisationFunctionalGroup() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionFunctionalisationFunctionalGroupEntry() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionCoatingSet() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionCoatingSetAtomicComposition() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition.Entry createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionCoatingSetAtomicCompositionEntry() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods createENDPOINTSTUDYRECORDSurfaceChemistryMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDSurfaceChemistryMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.TestMaterials.ReferenceMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.TestMaterials.ReferenceMaterial createENDPOINTSTUDYRECORDSurfaceChemistryMaterialsAndMethodsTestMaterialsReferenceMaterial() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.TestMaterials.ReferenceMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.Guidelines }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.Guidelines createENDPOINTSTUDYRECORDSurfaceChemistryMaterialsAndMethodsGuidelines() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.Guidelines();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.Guidelines.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.Guidelines.Entry createENDPOINTSTUDYRECORDSurfaceChemistryMaterialsAndMethodsGuidelinesEntry() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.Guidelines.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.DataSource createENDPOINTSTUDYRECORDSurfaceChemistryDataSource() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeData() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.AttachedJustification.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.DataProtection }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.DataProtection createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataDataProtection() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.DataProtection();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDSurfaceChemistryApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDSurfaceChemistryOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingFunctionalisation }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingFunctionalisation createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionCoatingFunctionalisation() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingFunctionalisation();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry.Group }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry.Group createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionFunctionalisationFunctionalGroupEntryGroup() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry.Group();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry.Fraction }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry.Fraction createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionFunctionalisationFunctionalGroupEntryFraction() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry.Fraction();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry.RemarksOnResults }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry.RemarksOnResults createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionFunctionalisationFunctionalGroupEntryRemarksOnResults() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry.RemarksOnResults();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.Coating }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.Coating createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionCoatingSetCoating() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.Coating();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition.Entry.Fraction }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition.Entry.Fraction createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionCoatingSetAtomicCompositionEntryFraction() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition.Entry.Fraction();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition.Entry.RemarksOnResults }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition.Entry.RemarksOnResults createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionCoatingSetAtomicCompositionEntryRemarksOnResults() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition.Entry.RemarksOnResults();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.GLPComplianceStatement }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.GLPComplianceStatement createENDPOINTSTUDYRECORDSurfaceChemistryMaterialsAndMethodsGLPComplianceStatement() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.GLPComplianceStatement();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.OtherQualityAssurance }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.OtherQualityAssurance createENDPOINTSTUDYRECORDSurfaceChemistryMaterialsAndMethodsOtherQualityAssurance() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.OtherQualityAssurance();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.MethodType }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.MethodType createENDPOINTSTUDYRECORDSurfaceChemistryMaterialsAndMethodsMethodType() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.MethodType();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.DataGathering }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.DataGathering createENDPOINTSTUDYRECORDSurfaceChemistryMaterialsAndMethodsDataGathering() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.DataGathering();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDSurfaceChemistryMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.TestMaterials.ReferenceMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.TestMaterials.ReferenceMaterial.Entry createENDPOINTSTUDYRECORDSurfaceChemistryMaterialsAndMethodsTestMaterialsReferenceMaterialEntry() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.TestMaterials.ReferenceMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.Guidelines.Entry.Qualifier }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.Guidelines.Entry.Qualifier createENDPOINTSTUDYRECORDSurfaceChemistryMaterialsAndMethodsGuidelinesEntryQualifier() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.Guidelines.Entry.Qualifier();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.Guidelines.Entry.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.Guidelines.Entry.Guideline createENDPOINTSTUDYRECORDSurfaceChemistryMaterialsAndMethodsGuidelinesEntryGuideline() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.Guidelines.Entry.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.Guidelines.Entry.Deviation }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.Guidelines.Entry.Deviation createENDPOINTSTUDYRECORDSurfaceChemistryMaterialsAndMethodsGuidelinesEntryDeviation() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.MaterialsAndMethods.Guidelines.Entry.Deviation();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.DataSource.DataAccess }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.DataSource.DataAccess createENDPOINTSTUDYRECORDSurfaceChemistryDataSourceDataAccess() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.DataSource.DataAccess();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.DataSource.DataProtectionClaimed }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.DataSource.DataProtectionClaimed createENDPOINTSTUDYRECORDSurfaceChemistryDataSourceDataProtectionClaimed() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.DataSource.DataProtectionClaimed();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.Endpoint }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.Endpoint createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataEndpoint() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.Endpoint();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.StudyResultType }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.StudyResultType createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataStudyResultType() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.StudyResultType();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.PurposeFlag }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.PurposeFlag createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataPurposeFlag() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.PurposeFlag();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.Reliability }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.Reliability createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataReliability() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.Reliability();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.RationalReliability }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.RationalReliability createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataRationalReliability() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.RationalReliability();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.DataWaiving }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.DataWaiving createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataDataWaiving() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.DataWaiving();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.DataWaivingJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.DataWaivingJustification createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataDataWaivingJustification() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.DataWaivingJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.CrossReference.Entry.ReasonPurpose }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.CrossReference.Entry.ReasonPurpose createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataCrossReferenceEntryReasonPurpose() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.CrossReference.Entry.ReasonPurpose();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.AttachedJustification.Entry.ReasonPurpose }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.AttachedJustification.Entry.ReasonPurpose createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataAttachedJustificationEntryReasonPurpose() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.AttachedJustification.Entry.ReasonPurpose();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.DataProtection.Legislation }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.DataProtection.Legislation createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataDataProtectionLegislation() {
        return new ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.DataProtection.Legislation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-SurfaceChemistry/5.0", name = "KeyResult", scope = ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionFunctionalisationFunctionalGroupEntryKeyResult(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionFunctionalisationFunctionalGroupEntryKeyResult_QNAME, Boolean.class, ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-SurfaceChemistry/5.0", name = "StDev", scope = ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry.class)
    public JAXBElement<BigDecimal> createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionFunctionalisationFunctionalGroupEntryStDev(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionFunctionalisationFunctionalGroupEntryStDev_QNAME, BigDecimal.class, ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.Functionalisation.FunctionalGroup.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-SurfaceChemistry/5.0", name = "KeyResult", scope = ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition.Entry.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionCoatingSetAtomicCompositionEntryKeyResult(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionFunctionalisationFunctionalGroupEntryKeyResult_QNAME, Boolean.class, ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-SurfaceChemistry/5.0", name = "StDev", scope = ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition.Entry.class)
    public JAXBElement<BigDecimal> createENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionCoatingSetAtomicCompositionEntryStDev(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ENDPOINTSTUDYRECORDSurfaceChemistryResultsAndDiscussionFunctionalisationFunctionalGroupEntryStDev_QNAME, BigDecimal.class, ENDPOINTSTUDYRECORDSurfaceChemistry.ResultsAndDiscussion.CoatingSet.AtomicComposition.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-SurfaceChemistry/5.0", name = "UsedForMSDS", scope = ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataUsedForMSDS(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataUsedForMSDS_QNAME, Boolean.class, ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-SurfaceChemistry/5.0", name = "UsedForClassification", scope = ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataUsedForClassification(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataUsedForClassification_QNAME, Boolean.class, ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-SurfaceChemistry/5.0", name = "RobustStudy", scope = ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataRobustStudy(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDSurfaceChemistryAdministrativeDataRobustStudy_QNAME, Boolean.class, ENDPOINTSTUDYRECORDSurfaceChemistry.AdministrativeData.class, value);
    }

}
