//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 04:38:05 PM EET 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_acutetoxicityoral._5;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_acutetoxicityoral._5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataUsedForClassification_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-AcuteToxicityOral/5.0", "UsedForClassification");
    private final static QName _ENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataUsedForMSDS_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-AcuteToxicityOral/5.0", "UsedForMSDS");
    private final static QName _ENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataRobustStudy_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-AcuteToxicityOral/5.0", "RobustStudy");
    private final static QName _ENDPOINTSTUDYRECORDAcuteToxicityOralResultsAndDiscussionEffectLevelsEntryKeyResult_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-AcuteToxicityOral/5.0", "KeyResult");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_acutetoxicityoral._5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral createENDPOINTSTUDYRECORDAcuteToxicityOral() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDAcuteToxicityOralApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.OverallRemarksAttachments createENDPOINTSTUDYRECORDAcuteToxicityOralOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDAcuteToxicityOralOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion createENDPOINTSTUDYRECORDAcuteToxicityOralResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels createENDPOINTSTUDYRECORDAcuteToxicityOralResultsAndDiscussionEffectLevels() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry createENDPOINTSTUDYRECORDAcuteToxicityOralResultsAndDiscussionEffectLevelsEntry() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.AdministrationExposure }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.AdministrationExposure createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsAdministrationExposure() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.AdministrationExposure();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestAnimals }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestAnimals createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsTestAnimals() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestAnimals();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.Guidelines }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.Guidelines createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsGuidelines() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.Guidelines();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.Guidelines.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.Guidelines.Entry createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsGuidelinesEntry() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.Guidelines.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.DataSource createENDPOINTSTUDYRECORDAcuteToxicityOralDataSource() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeData() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.AttachedJustification.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.DataProtection }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.DataProtection createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataDataProtection() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.DataProtection();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.ApplicantSummaryAndConclusion.InterpretationOfResults }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.ApplicantSummaryAndConclusion.InterpretationOfResults createENDPOINTSTUDYRECORDAcuteToxicityOralApplicantSummaryAndConclusionInterpretationOfResults() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.ApplicantSummaryAndConclusion.InterpretationOfResults();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDAcuteToxicityOralOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDAcuteToxicityOralResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.Sex }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.Sex createENDPOINTSTUDYRECORDAcuteToxicityOralResultsAndDiscussionEffectLevelsEntrySex() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.Sex();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.Endpoint }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.Endpoint createENDPOINTSTUDYRECORDAcuteToxicityOralResultsAndDiscussionEffectLevelsEntryEndpoint() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.Endpoint();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.EffectLevel }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.EffectLevel createENDPOINTSTUDYRECORDAcuteToxicityOralResultsAndDiscussionEffectLevelsEntryEffectLevel() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.EffectLevel();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.BasedOn }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.BasedOn createENDPOINTSTUDYRECORDAcuteToxicityOralResultsAndDiscussionEffectLevelsEntryBasedOn() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.BasedOn();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.Cl }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.Cl createENDPOINTSTUDYRECORDAcuteToxicityOralResultsAndDiscussionEffectLevelsEntryCl() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.Cl();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.RemarksOnResults }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.RemarksOnResults createENDPOINTSTUDYRECORDAcuteToxicityOralResultsAndDiscussionEffectLevelsEntryRemarksOnResults() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.RemarksOnResults();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.GLPComplianceStatement }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.GLPComplianceStatement createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsGLPComplianceStatement() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.GLPComplianceStatement();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestType }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestType createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsTestType() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestType();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.LimitTest }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.LimitTest createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsLimitTest() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.LimitTest();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.AdministrationExposure.RouteOfAdministration }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.AdministrationExposure.RouteOfAdministration createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsAdministrationExposureRouteOfAdministration() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.AdministrationExposure.RouteOfAdministration();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.AdministrationExposure.Vehicle }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.AdministrationExposure.Vehicle createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsAdministrationExposureVehicle() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.AdministrationExposure.Vehicle();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.AdministrationExposure.ControlAnimals }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.AdministrationExposure.ControlAnimals createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsAdministrationExposureControlAnimals() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.AdministrationExposure.ControlAnimals();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestAnimals.Species }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestAnimals.Species createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsTestAnimalsSpecies() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestAnimals.Species();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestAnimals.Strain }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestAnimals.Strain createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsTestAnimalsStrain() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestAnimals.Strain();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestAnimals.Sex }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestAnimals.Sex createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsTestAnimalsSex() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.TestAnimals.Sex();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.Guidelines.Entry.Qualifier }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.Guidelines.Entry.Qualifier createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsGuidelinesEntryQualifier() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.Guidelines.Entry.Qualifier();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.Guidelines.Entry.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.Guidelines.Entry.Guideline createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsGuidelinesEntryGuideline() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.Guidelines.Entry.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.Guidelines.Entry.Deviation }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.Guidelines.Entry.Deviation createENDPOINTSTUDYRECORDAcuteToxicityOralMaterialsAndMethodsGuidelinesEntryDeviation() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.MaterialsAndMethods.Guidelines.Entry.Deviation();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.DataSource.DataAccess }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.DataSource.DataAccess createENDPOINTSTUDYRECORDAcuteToxicityOralDataSourceDataAccess() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.DataSource.DataAccess();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.DataSource.DataProtectionClaimed }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.DataSource.DataProtectionClaimed createENDPOINTSTUDYRECORDAcuteToxicityOralDataSourceDataProtectionClaimed() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.DataSource.DataProtectionClaimed();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.Endpoint }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.Endpoint createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataEndpoint() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.Endpoint();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.StudyResultType }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.StudyResultType createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataStudyResultType() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.StudyResultType();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.PurposeFlag }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.PurposeFlag createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataPurposeFlag() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.PurposeFlag();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.Reliability }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.Reliability createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataReliability() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.Reliability();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.RationalReliability }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.RationalReliability createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataRationalReliability() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.RationalReliability();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.DataWaiving }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.DataWaiving createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataDataWaiving() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.DataWaiving();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.DataWaivingJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.DataWaivingJustification createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataDataWaivingJustification() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.DataWaivingJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.CrossReference.Entry.ReasonPurpose }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.CrossReference.Entry.ReasonPurpose createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataCrossReferenceEntryReasonPurpose() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.CrossReference.Entry.ReasonPurpose();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.AttachedJustification.Entry.ReasonPurpose }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.AttachedJustification.Entry.ReasonPurpose createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataAttachedJustificationEntryReasonPurpose() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.AttachedJustification.Entry.ReasonPurpose();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.DataProtection.Legislation }
     * 
     */
    public ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.DataProtection.Legislation createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataDataProtectionLegislation() {
        return new ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.DataProtection.Legislation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-AcuteToxicityOral/5.0", name = "UsedForClassification", scope = ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataUsedForClassification(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataUsedForClassification_QNAME, Boolean.class, ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-AcuteToxicityOral/5.0", name = "UsedForMSDS", scope = ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataUsedForMSDS(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataUsedForMSDS_QNAME, Boolean.class, ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-AcuteToxicityOral/5.0", name = "RobustStudy", scope = ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataRobustStudy(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDAcuteToxicityOralAdministrativeDataRobustStudy_QNAME, Boolean.class, ENDPOINTSTUDYRECORDAcuteToxicityOral.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-AcuteToxicityOral/5.0", name = "KeyResult", scope = ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDAcuteToxicityOralResultsAndDiscussionEffectLevelsEntryKeyResult(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDAcuteToxicityOralResultsAndDiscussionEffectLevelsEntryKeyResult_QNAME, Boolean.class, ENDPOINTSTUDYRECORDAcuteToxicityOral.ResultsAndDiscussion.EffectLevels.Entry.class, value);
    }

}
