//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.01 at 08:47:32 PM EEST 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_surfacetension._2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_surfacetension._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_surfacetension._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension createENDPOINTSTUDYRECORDSurfaceTension() {
        return new ENDPOINTSTUDYRECORDSurfaceTension();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.OverallRemarksAttachments createENDPOINTSTUDYRECORDSurfaceTensionOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDSurfaceTensionOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion createENDPOINTSTUDYRECORDSurfaceTensionResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion.SurfaceTension }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion.SurfaceTension createENDPOINTSTUDYRECORDSurfaceTensionResultsAndDiscussionSurfaceTension() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion.SurfaceTension();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion.SurfaceTension.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion.SurfaceTension.Entry createENDPOINTSTUDYRECORDSurfaceTensionResultsAndDiscussionSurfaceTensionEntry() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion.SurfaceTension.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods createENDPOINTSTUDYRECORDSurfaceTensionMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods.Guideline createENDPOINTSTUDYRECORDSurfaceTensionMaterialsAndMethodsGuideline() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.AdministrativeData createENDPOINTSTUDYRECORDSurfaceTensionAdministrativeData() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDSurfaceTensionAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDSurfaceTensionAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.DataSource createENDPOINTSTUDYRECORDSurfaceTensionDataSource() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDSurfaceTensionApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDSurfaceTensionOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDSurfaceTensionResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion.SurfaceTension.Entry.Temp }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion.SurfaceTension.Entry.Temp createENDPOINTSTUDYRECORDSurfaceTensionResultsAndDiscussionSurfaceTensionEntryTemp() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion.SurfaceTension.Entry.Temp();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion.SurfaceTension.Entry.Conc }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion.SurfaceTension.Entry.Conc createENDPOINTSTUDYRECORDSurfaceTensionResultsAndDiscussionSurfaceTensionEntryConc() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.ResultsAndDiscussion.SurfaceTension.Entry.Conc();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDSurfaceTensionMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods.StudyDesign }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods.StudyDesign createENDPOINTSTUDYRECORDSurfaceTensionMaterialsAndMethodsStudyDesign() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods.StudyDesign();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDSurfaceTensionMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods.Guideline.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods.Guideline.Entry createENDPOINTSTUDYRECORDSurfaceTensionMaterialsAndMethodsGuidelineEntry() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.MaterialsAndMethods.Guideline.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDSurfaceTensionAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSurfaceTension.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSurfaceTension.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDSurfaceTensionAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDSurfaceTension.AdministrativeData.AttachedJustification.Entry();
    }

}
