//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.01 at 08:45:58 PM EEST 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_bioaccumulationaquaticsediment._2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_bioaccumulationaquaticsediment._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_bioaccumulationaquaticsediment._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment createENDPOINTSTUDYRECORDBioaccumulationAquaticSediment() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.OverallRemarksAttachments createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.RateConstants }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.RateConstants createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentResultsAndDiscussionRateConstants() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.RateConstants();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.Depuration }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.Depuration createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentResultsAndDiscussionDepuration() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.Depuration();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.Depuration.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.Depuration.Entry createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentResultsAndDiscussionDepurationEntry() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.Depuration.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.BioaccumulationFactor }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.BioaccumulationFactor createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentResultsAndDiscussionBioaccumulationFactor() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.BioaccumulationFactor();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.BioaccumulationFactor.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.BioaccumulationFactor.Entry createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentResultsAndDiscussionBioaccumulationFactorEntry() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.BioaccumulationFactor.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.LipidContent }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.LipidContent createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentResultsAndDiscussionLipidContent() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.LipidContent();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.Guideline createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentMaterialsAndMethodsGuideline() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.AdministrativeData createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentAdministrativeData() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.DataSource createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentDataSource() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.RateConstants.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.RateConstants.Entry createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentResultsAndDiscussionRateConstantsEntry() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.RateConstants.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.Depuration.Entry.DepurationTime }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.Depuration.Entry.DepurationTime createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentResultsAndDiscussionDepurationEntryDepurationTime() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.Depuration.Entry.DepurationTime();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.BioaccumulationFactor.Entry.TimeOfPlateau }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.BioaccumulationFactor.Entry.TimeOfPlateau createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentResultsAndDiscussionBioaccumulationFactorEntryTimeOfPlateau() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.BioaccumulationFactor.Entry.TimeOfPlateau();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.LipidContent.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.LipidContent.Entry createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentResultsAndDiscussionLipidContentEntry() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.ResultsAndDiscussion.LipidContent.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.SamplingAndAnalysis }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.SamplingAndAnalysis createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentMaterialsAndMethodsSamplingAndAnalysis() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.SamplingAndAnalysis();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.TestSolutions }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.TestSolutions createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentMaterialsAndMethodsTestSolutions() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.TestSolutions();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.TestOrganisms }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.TestOrganisms createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentMaterialsAndMethodsTestOrganisms() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.TestOrganisms();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.StudyDesign }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.StudyDesign createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentMaterialsAndMethodsStudyDesign() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.StudyDesign();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.TestConditions }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.TestConditions createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentMaterialsAndMethodsTestConditions() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.TestConditions();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.Guideline.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.Guideline.Entry createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentMaterialsAndMethodsGuidelineEntry() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.MaterialsAndMethods.Guideline.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDBioaccumulationAquaticSedimentAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDBioaccumulationAquaticSediment.AdministrativeData.AttachedJustification.Entry();
    }

}
