//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.01 at 08:46:57 PM EEST 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_photocatalyticactivity._2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_photocatalyticactivity._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_photocatalyticactivity._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity createENDPOINTSTUDYRECORDPhotocatalyticActivity() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.OverallRemarksAttachments createENDPOINTSTUDYRECORDPhotocatalyticActivityOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDPhotocatalyticActivityOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion createENDPOINTSTUDYRECORDPhotocatalyticActivityResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.TurnOverFrequency }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.TurnOverFrequency createENDPOINTSTUDYRECORDPhotocatalyticActivityResultsAndDiscussionTurnOverFrequency() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.TurnOverFrequency();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.TurnOverFrequency.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.TurnOverFrequency.Entry createENDPOINTSTUDYRECORDPhotocatalyticActivityResultsAndDiscussionTurnOverFrequencyEntry() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.TurnOverFrequency.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.PhotocatalyticActivity }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.PhotocatalyticActivity createENDPOINTSTUDYRECORDPhotocatalyticActivityResultsAndDiscussionPhotocatalyticActivity() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.PhotocatalyticActivity();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.PhotocatalyticActivity.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.PhotocatalyticActivity.Entry createENDPOINTSTUDYRECORDPhotocatalyticActivityResultsAndDiscussionPhotocatalyticActivityEntry() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.PhotocatalyticActivity.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods createENDPOINTSTUDYRECORDPhotocatalyticActivityMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDPhotocatalyticActivityMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.TestMaterials.ReferenceMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.TestMaterials.ReferenceMaterial createENDPOINTSTUDYRECORDPhotocatalyticActivityMaterialsAndMethodsTestMaterialsReferenceMaterial() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.TestMaterials.ReferenceMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.Guideline createENDPOINTSTUDYRECORDPhotocatalyticActivityMaterialsAndMethodsGuideline() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.AdministrativeData createENDPOINTSTUDYRECORDPhotocatalyticActivityAdministrativeData() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDPhotocatalyticActivityAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDPhotocatalyticActivityAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.DataSource createENDPOINTSTUDYRECORDPhotocatalyticActivityDataSource() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDPhotocatalyticActivityApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDPhotocatalyticActivityOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDPhotocatalyticActivityResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.TurnOverFrequency.Entry.StDev }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.TurnOverFrequency.Entry.StDev createENDPOINTSTUDYRECORDPhotocatalyticActivityResultsAndDiscussionTurnOverFrequencyEntryStDev() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.TurnOverFrequency.Entry.StDev();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.PhotocatalyticActivity.Entry.StDev }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.PhotocatalyticActivity.Entry.StDev createENDPOINTSTUDYRECORDPhotocatalyticActivityResultsAndDiscussionPhotocatalyticActivityEntryStDev() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.ResultsAndDiscussion.PhotocatalyticActivity.Entry.StDev();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.DataGathering }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.DataGathering createENDPOINTSTUDYRECORDPhotocatalyticActivityMaterialsAndMethodsDataGathering() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.DataGathering();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDPhotocatalyticActivityMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.TestMaterials.ReferenceMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.TestMaterials.ReferenceMaterial.Entry createENDPOINTSTUDYRECORDPhotocatalyticActivityMaterialsAndMethodsTestMaterialsReferenceMaterialEntry() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.TestMaterials.ReferenceMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.Guideline.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.Guideline.Entry createENDPOINTSTUDYRECORDPhotocatalyticActivityMaterialsAndMethodsGuidelineEntry() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.MaterialsAndMethods.Guideline.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDPhotocatalyticActivityAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotocatalyticActivity.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotocatalyticActivity.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDPhotocatalyticActivityAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDPhotocatalyticActivity.AdministrativeData.AttachedJustification.Entry();
    }

}
