//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.27 at 11:13:02 PM EET 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_analyticalmethods._5;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_analyticalmethods._5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataRobustStudy_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-AnalyticalMethods/5.0", "RobustStudy");
    private final static QName _ENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataUsedForMSDS_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-AnalyticalMethods/5.0", "UsedForMSDS");
    private final static QName _ENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataUsedForClassification_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-AnalyticalMethods/5.0", "UsedForClassification");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_analyticalmethods._5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods createENDPOINTSTUDYRECORDAnalyticalMethods() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.OverallRemarksAttachments createENDPOINTSTUDYRECORDAnalyticalMethodsOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDAnalyticalMethodsOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.ResultsAndDiscussion createENDPOINTSTUDYRECORDAnalyticalMethodsResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.ConfirmatoryMethodIfApplicable }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.ConfirmatoryMethodIfApplicable createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsConfirmatoryMethodIfApplicable() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.ConfirmatoryMethodIfApplicable();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.EnforcementMethodIfApplicable }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.EnforcementMethodIfApplicable createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsEnforcementMethodIfApplicable() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.EnforcementMethodIfApplicable();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.PrinciplesOfAnalyticalMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.PrinciplesOfAnalyticalMethods createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsPrinciplesOfAnalyticalMethods() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.PrinciplesOfAnalyticalMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.Guidelines }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.Guidelines createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsGuidelines() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.Guidelines();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.Guidelines.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.Guidelines.Entry createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsGuidelinesEntry() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.Guidelines.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.DataSource createENDPOINTSTUDYRECORDAnalyticalMethodsDataSource() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeData() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.AttachedJustification.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.DataProtection }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.DataProtection createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataDataProtection() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.DataProtection();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.Background }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.Background createENDPOINTSTUDYRECORDAnalyticalMethodsBackground() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.Background();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDAnalyticalMethodsApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDAnalyticalMethodsOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.ResultsAndDiscussion.RecoveryResultsAndCharacteristicsOfAnalyticalMethod }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.ResultsAndDiscussion.RecoveryResultsAndCharacteristicsOfAnalyticalMethod createENDPOINTSTUDYRECORDAnalyticalMethodsResultsAndDiscussionRecoveryResultsAndCharacteristicsOfAnalyticalMethod() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.ResultsAndDiscussion.RecoveryResultsAndCharacteristicsOfAnalyticalMethod();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.ResultsAndDiscussion.ResultsUsingEnforcementMethod }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.ResultsAndDiscussion.ResultsUsingEnforcementMethod createENDPOINTSTUDYRECORDAnalyticalMethodsResultsAndDiscussionResultsUsingEnforcementMethod() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.ResultsAndDiscussion.ResultsUsingEnforcementMethod();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.ResultsAndDiscussion.IndependentLaboratoryValidation }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.ResultsAndDiscussion.IndependentLaboratoryValidation createENDPOINTSTUDYRECORDAnalyticalMethodsResultsAndDiscussionIndependentLaboratoryValidation() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.ResultsAndDiscussion.IndependentLaboratoryValidation();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDAnalyticalMethodsResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.GLPComplianceStatement }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.GLPComplianceStatement createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsGLPComplianceStatement() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.GLPComplianceStatement();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.OtherQualityAssurance }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.OtherQualityAssurance createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsOtherQualityAssurance() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.OtherQualityAssurance();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.MatrixMedium }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.MatrixMedium createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsMatrixMedium() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.MatrixMedium();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.ConfirmatoryMethodIfApplicable.InstrumentDetectorForConfirmatoryMethod }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.ConfirmatoryMethodIfApplicable.InstrumentDetectorForConfirmatoryMethod createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsConfirmatoryMethodIfApplicableInstrumentDetectorForConfirmatoryMethod() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.ConfirmatoryMethodIfApplicable.InstrumentDetectorForConfirmatoryMethod();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.EnforcementMethodIfApplicable.InstrumentDetectorForEnforcementMethod }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.EnforcementMethodIfApplicable.InstrumentDetectorForEnforcementMethod createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsEnforcementMethodIfApplicableInstrumentDetectorForEnforcementMethod() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.EnforcementMethodIfApplicable.InstrumentDetectorForEnforcementMethod();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.PrinciplesOfAnalyticalMethods.InstrumentDetector }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.PrinciplesOfAnalyticalMethods.InstrumentDetector createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsPrinciplesOfAnalyticalMethodsInstrumentDetector() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.PrinciplesOfAnalyticalMethods.InstrumentDetector();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.Guidelines.Entry.Qualifier }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.Guidelines.Entry.Qualifier createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsGuidelinesEntryQualifier() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.Guidelines.Entry.Qualifier();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.Guidelines.Entry.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.Guidelines.Entry.Guideline createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsGuidelinesEntryGuideline() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.Guidelines.Entry.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.Guidelines.Entry.Deviation }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.Guidelines.Entry.Deviation createENDPOINTSTUDYRECORDAnalyticalMethodsMaterialsAndMethodsGuidelinesEntryDeviation() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.MaterialsAndMethods.Guidelines.Entry.Deviation();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.DataSource.DataAccess }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.DataSource.DataAccess createENDPOINTSTUDYRECORDAnalyticalMethodsDataSourceDataAccess() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.DataSource.DataAccess();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.DataSource.DataProtectionClaimed }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.DataSource.DataProtectionClaimed createENDPOINTSTUDYRECORDAnalyticalMethodsDataSourceDataProtectionClaimed() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.DataSource.DataProtectionClaimed();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.Endpoint }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.Endpoint createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataEndpoint() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.Endpoint();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.StudyResultType }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.StudyResultType createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataStudyResultType() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.StudyResultType();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.PurposeFlag }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.PurposeFlag createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataPurposeFlag() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.PurposeFlag();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.Reliability }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.Reliability createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataReliability() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.Reliability();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.RationalReliability }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.RationalReliability createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataRationalReliability() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.RationalReliability();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.DataWaiving }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.DataWaiving createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataDataWaiving() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.DataWaiving();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.DataWaivingJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.DataWaivingJustification createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataDataWaivingJustification() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.DataWaivingJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.CrossReference.Entry.ReasonPurpose }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.CrossReference.Entry.ReasonPurpose createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataCrossReferenceEntryReasonPurpose() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.CrossReference.Entry.ReasonPurpose();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.AttachedJustification.Entry.ReasonPurpose }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.AttachedJustification.Entry.ReasonPurpose createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataAttachedJustificationEntryReasonPurpose() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.AttachedJustification.Entry.ReasonPurpose();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.DataProtection.Legislation }
     * 
     */
    public ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.DataProtection.Legislation createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataDataProtectionLegislation() {
        return new ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.DataProtection.Legislation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-AnalyticalMethods/5.0", name = "RobustStudy", scope = ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataRobustStudy(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataRobustStudy_QNAME, Boolean.class, ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-AnalyticalMethods/5.0", name = "UsedForMSDS", scope = ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataUsedForMSDS(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataUsedForMSDS_QNAME, Boolean.class, ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-AnalyticalMethods/5.0", name = "UsedForClassification", scope = ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataUsedForClassification(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDAnalyticalMethodsAdministrativeDataUsedForClassification_QNAME, Boolean.class, ENDPOINTSTUDYRECORDAnalyticalMethods.AdministrativeData.class, value);
    }

}
