//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.27 at 11:17:45 PM EET 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_stabilityofresiduesinstoredcommod._5;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_stabilityofresiduesinstoredcommod._5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryExtractionDate_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", "ExtractionDate");
    private final static QName _ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryMeanResidueLevelOfNominalSpikingLevel_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", "MeanResidueLevelOfNominalSpikingLevel");
    private final static QName _ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryAnalysisDate_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", "AnalysisDate");
    private final static QName _ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryMeanProceduralRecoveryControl_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", "MeanProceduralRecoveryControl");
    private final static QName _ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataRobustStudy_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", "RobustStudy");
    private final static QName _ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataUsedForClassification_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", "UsedForClassification");
    private final static QName _ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataUsedForMSDS_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", "UsedForMSDS");
    private final static QName _ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetDateOfSample_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", "DateOfSample");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_stabilityofresiduesinstoredcommod._5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.OverallRemarksAttachments createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevels() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySet() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasured() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntry() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.StudyDesign }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.StudyDesign createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodMaterialsAndMethodsStudyDesign() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.StudyDesign();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.Guidelines }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.Guidelines createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodMaterialsAndMethodsGuidelines() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.Guidelines();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.Guidelines.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.Guidelines.Entry createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodMaterialsAndMethodsGuidelinesEntry() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.Guidelines.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.DataSource createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodDataSource() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeData() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.AttachedJustification.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.DataProtection }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.DataProtection createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataDataProtection() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.DataProtection();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.TestCommodity }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.TestCommodity createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetTestCommodity() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.TestCommodity();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.ResidueLevel }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.ResidueLevel createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryResidueLevel() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.ResidueLevel();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.MeanResidueLevel }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.MeanResidueLevel createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryMeanResidueLevel() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.MeanResidueLevel();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.ResidueLevelOfNominalSpikingLevel }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.ResidueLevelOfNominalSpikingLevel createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryResidueLevelOfNominalSpikingLevel() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.ResidueLevelOfNominalSpikingLevel();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.ProceduralRecoveryControl }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.ProceduralRecoveryControl createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryProceduralRecoveryControl() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.ProceduralRecoveryControl();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.ProductType }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.ProductType createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodMaterialsAndMethodsProductType() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.ProductType();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.GLPComplianceStatement }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.GLPComplianceStatement createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodMaterialsAndMethodsGLPComplianceStatement() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.GLPComplianceStatement();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.SamplingAndAnalyticalMethodology }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.SamplingAndAnalyticalMethodology createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodMaterialsAndMethodsSamplingAndAnalyticalMethodology() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.SamplingAndAnalyticalMethodology();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.StudyDesign.Commodity }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.StudyDesign.Commodity createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodMaterialsAndMethodsStudyDesignCommodity() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.StudyDesign.Commodity();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.TestMaterials.Radiolabelling }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.TestMaterials.Radiolabelling createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodMaterialsAndMethodsTestMaterialsRadiolabelling() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.TestMaterials.Radiolabelling();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.Guidelines.Entry.Qualifier }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.Guidelines.Entry.Qualifier createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodMaterialsAndMethodsGuidelinesEntryQualifier() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.Guidelines.Entry.Qualifier();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.Guidelines.Entry.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.Guidelines.Entry.Guideline createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodMaterialsAndMethodsGuidelinesEntryGuideline() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.Guidelines.Entry.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.Guidelines.Entry.Deviation }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.Guidelines.Entry.Deviation createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodMaterialsAndMethodsGuidelinesEntryDeviation() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.MaterialsAndMethods.Guidelines.Entry.Deviation();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.DataSource.DataAccess }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.DataSource.DataAccess createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodDataSourceDataAccess() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.DataSource.DataAccess();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.DataSource.DataProtectionClaimed }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.DataSource.DataProtectionClaimed createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodDataSourceDataProtectionClaimed() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.DataSource.DataProtectionClaimed();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.Endpoint }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.Endpoint createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataEndpoint() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.Endpoint();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.StudyResultType }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.StudyResultType createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataStudyResultType() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.StudyResultType();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.PurposeFlag }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.PurposeFlag createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataPurposeFlag() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.PurposeFlag();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.Reliability }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.Reliability createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataReliability() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.Reliability();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.RationalReliability }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.RationalReliability createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataRationalReliability() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.RationalReliability();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.DataWaiving }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.DataWaiving createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataDataWaiving() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.DataWaiving();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.DataWaivingJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.DataWaivingJustification createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataDataWaivingJustification() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.DataWaivingJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.CrossReference.Entry.ReasonPurpose }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.CrossReference.Entry.ReasonPurpose createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataCrossReferenceEntryReasonPurpose() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.CrossReference.Entry.ReasonPurpose();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.AttachedJustification.Entry.ReasonPurpose }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.AttachedJustification.Entry.ReasonPurpose createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataAttachedJustificationEntryReasonPurpose() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.AttachedJustification.Entry.ReasonPurpose();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.DataProtection.Legislation }
     * 
     */
    public ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.DataProtection.Legislation createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataDataProtectionLegislation() {
        return new ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.DataProtection.Legislation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", name = "ExtractionDate", scope = ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.class)
    public JAXBElement<XMLGregorianCalendar> createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryExtractionDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryExtractionDate_QNAME, XMLGregorianCalendar.class, ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", name = "MeanResidueLevelOfNominalSpikingLevel", scope = ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.class)
    public JAXBElement<BigDecimal> createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryMeanResidueLevelOfNominalSpikingLevel(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryMeanResidueLevelOfNominalSpikingLevel_QNAME, BigDecimal.class, ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", name = "AnalysisDate", scope = ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.class)
    public JAXBElement<XMLGregorianCalendar> createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryAnalysisDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryAnalysisDate_QNAME, XMLGregorianCalendar.class, ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", name = "MeanProceduralRecoveryControl", scope = ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.class)
    public JAXBElement<BigDecimal> createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryMeanProceduralRecoveryControl(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetAnalyteMeasuredEntryMeanProceduralRecoveryControl_QNAME, BigDecimal.class, ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.AnalyteMeasured.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", name = "RobustStudy", scope = ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataRobustStudy(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataRobustStudy_QNAME, Boolean.class, ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", name = "UsedForClassification", scope = ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataUsedForClassification(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataUsedForClassification_QNAME, Boolean.class, ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", name = "UsedForMSDS", scope = ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataUsedForMSDS(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodAdministrativeDataUsedForMSDS_QNAME, Boolean.class, ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-StabilityOfResiduesInStoredCommod/5.0", name = "DateOfSample", scope = ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.class)
    public JAXBElement<XMLGregorianCalendar> createENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetDateOfSample(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommodResultsAndDiscussionResidueLevelsEntrySetDateOfSample_QNAME, XMLGregorianCalendar.class, ENDPOINTSTUDYRECORDStabilityOfResiduesInStoredCommod.ResultsAndDiscussion.ResidueLevels.EntrySet.class, value);
    }

}
