//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.27 at 11:24:54 PM EET 
//


package eu.europa.echa.iuclid6.namespaces.site._5;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.site._5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.site._5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SITE }
     * 
     */
    public SITE createSITE() {
        return new SITE();
    }

    /**
     * Create an instance of {@link SITE.ContactAddress }
     * 
     */
    public SITE.ContactAddress createSITEContactAddress() {
        return new SITE.ContactAddress();
    }

    /**
     * Create an instance of {@link SITE.ContactAddress.DataProtection }
     * 
     */
    public SITE.ContactAddress.DataProtection createSITEContactAddressDataProtection() {
        return new SITE.ContactAddress.DataProtection();
    }

    /**
     * Create an instance of {@link SITE.GeneralInfo }
     * 
     */
    public SITE.GeneralInfo createSITEGeneralInfo() {
        return new SITE.GeneralInfo();
    }

    /**
     * Create an instance of {@link SITE.GeneralInfo.ExternalSystemIdentifiers }
     * 
     */
    public SITE.GeneralInfo.ExternalSystemIdentifiers createSITEGeneralInfoExternalSystemIdentifiers() {
        return new SITE.GeneralInfo.ExternalSystemIdentifiers();
    }

    /**
     * Create an instance of {@link SITE.GeneralInfo.ExternalSystemIdentifiers.Entry }
     * 
     */
    public SITE.GeneralInfo.ExternalSystemIdentifiers.Entry createSITEGeneralInfoExternalSystemIdentifiersEntry() {
        return new SITE.GeneralInfo.ExternalSystemIdentifiers.Entry();
    }

    /**
     * Create an instance of {@link SITE.GeneralInfo.ExternalSystemIdentifiers.Entry.DataProtection }
     * 
     */
    public SITE.GeneralInfo.ExternalSystemIdentifiers.Entry.DataProtection createSITEGeneralInfoExternalSystemIdentifiersEntryDataProtection() {
        return new SITE.GeneralInfo.ExternalSystemIdentifiers.Entry.DataProtection();
    }

    /**
     * Create an instance of {@link SITE.ConfidentialityInfo }
     * 
     */
    public SITE.ConfidentialityInfo createSITEConfidentialityInfo() {
        return new SITE.ConfidentialityInfo();
    }

    /**
     * Create an instance of {@link SITE.ConfidentialityInfo.DataProtection }
     * 
     */
    public SITE.ConfidentialityInfo.DataProtection createSITEConfidentialityInfoDataProtection() {
        return new SITE.ConfidentialityInfo.DataProtection();
    }

    /**
     * Create an instance of {@link SITE.ContactAddress.DataProtection.Legislation }
     * 
     */
    public SITE.ContactAddress.DataProtection.Legislation createSITEContactAddressDataProtectionLegislation() {
        return new SITE.ContactAddress.DataProtection.Legislation();
    }

    /**
     * Create an instance of {@link SITE.GeneralInfo.ExternalSystemIdentifiers.Entry.DataProtection.Legislation }
     * 
     */
    public SITE.GeneralInfo.ExternalSystemIdentifiers.Entry.DataProtection.Legislation createSITEGeneralInfoExternalSystemIdentifiersEntryDataProtectionLegislation() {
        return new SITE.GeneralInfo.ExternalSystemIdentifiers.Entry.DataProtection.Legislation();
    }

    /**
     * Create an instance of {@link SITE.ConfidentialityInfo.DataProtection.Legislation }
     * 
     */
    public SITE.ConfidentialityInfo.DataProtection.Legislation createSITEConfidentialityInfoDataProtectionLegislation() {
        return new SITE.ConfidentialityInfo.DataProtection.Legislation();
    }

}
