//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.27 at 11:12:13 PM EET 
//


package eu.europa.echa.iuclid6.namespaces.category._5;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.category._5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.category._5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CATEGORY }
     * 
     */
    public CATEGORY createCATEGORY() {
        return new CATEGORY();
    }

    /**
     * Create an instance of {@link CATEGORY.JustificationsAndDiscussions }
     * 
     */
    public CATEGORY.JustificationsAndDiscussions createCATEGORYJustificationsAndDiscussions() {
        return new CATEGORY.JustificationsAndDiscussions();
    }

    /**
     * Create an instance of {@link CATEGORY.JustificationsAndDiscussions.Reports }
     * 
     */
    public CATEGORY.JustificationsAndDiscussions.Reports createCATEGORYJustificationsAndDiscussionsReports() {
        return new CATEGORY.JustificationsAndDiscussions.Reports();
    }

    /**
     * Create an instance of {@link CATEGORY.JustificationsAndDiscussions.Reports.Entry }
     * 
     */
    public CATEGORY.JustificationsAndDiscussions.Reports.Entry createCATEGORYJustificationsAndDiscussionsReportsEntry() {
        return new CATEGORY.JustificationsAndDiscussions.Reports.Entry();
    }

    /**
     * Create an instance of {@link CATEGORY.JustificationsAndDiscussions.Reports.Entry.Flags }
     * 
     */
    public CATEGORY.JustificationsAndDiscussions.Reports.Entry.Flags createCATEGORYJustificationsAndDiscussionsReportsEntryFlags() {
        return new CATEGORY.JustificationsAndDiscussions.Reports.Entry.Flags();
    }

    /**
     * Create an instance of {@link CATEGORY.RegulatoryPurposes }
     * 
     */
    public CATEGORY.RegulatoryPurposes createCATEGORYRegulatoryPurposes() {
        return new CATEGORY.RegulatoryPurposes();
    }

    /**
     * Create an instance of {@link CATEGORY.CategoryDocuments }
     * 
     */
    public CATEGORY.CategoryDocuments createCATEGORYCategoryDocuments() {
        return new CATEGORY.CategoryDocuments();
    }

    /**
     * Create an instance of {@link CATEGORY.JustificationsAndDiscussions.Reports.Entry.Flags.Legislation }
     * 
     */
    public CATEGORY.JustificationsAndDiscussions.Reports.Entry.Flags.Legislation createCATEGORYJustificationsAndDiscussionsReportsEntryFlagsLegislation() {
        return new CATEGORY.JustificationsAndDiscussions.Reports.Entry.Flags.Legislation();
    }

}
