//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.01 at 08:45:56 PM EEST 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_aspectratioshape._2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_aspectratioshape._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_aspectratioshape._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape createENDPOINTSTUDYRECORDAspectRatioShape() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.OverallRemarksAttachments createENDPOINTSTUDYRECORDAspectRatioShapeOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDAspectRatioShapeOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion createENDPOINTSTUDYRECORDAspectRatioShapeResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.AspectRatio }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.AspectRatio createENDPOINTSTUDYRECORDAspectRatioShapeResultsAndDiscussionAspectRatio() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.AspectRatio();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.ShapeDescription }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.ShapeDescription createENDPOINTSTUDYRECORDAspectRatioShapeResultsAndDiscussionShapeDescription() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.ShapeDescription();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.ShapeDescription.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.ShapeDescription.Entry createENDPOINTSTUDYRECORDAspectRatioShapeResultsAndDiscussionShapeDescriptionEntry() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.ShapeDescription.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods createENDPOINTSTUDYRECORDAspectRatioShapeMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDAspectRatioShapeMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.TestMaterials.ReferenceMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.TestMaterials.ReferenceMaterial createENDPOINTSTUDYRECORDAspectRatioShapeMaterialsAndMethodsTestMaterialsReferenceMaterial() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.TestMaterials.ReferenceMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.Guideline createENDPOINTSTUDYRECORDAspectRatioShapeMaterialsAndMethodsGuideline() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.AdministrativeData createENDPOINTSTUDYRECORDAspectRatioShapeAdministrativeData() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDAspectRatioShapeAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDAspectRatioShapeAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.DataSource createENDPOINTSTUDYRECORDAspectRatioShapeDataSource() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDAspectRatioShapeApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDAspectRatioShapeOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDAspectRatioShapeResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.AspectRatio.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.AspectRatio.Entry createENDPOINTSTUDYRECORDAspectRatioShapeResultsAndDiscussionAspectRatioEntry() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.AspectRatio.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.ShapeDescription.Entry.PercentageValue }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.ShapeDescription.Entry.PercentageValue createENDPOINTSTUDYRECORDAspectRatioShapeResultsAndDiscussionShapeDescriptionEntryPercentageValue() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.ShapeDescription.Entry.PercentageValue();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.ShapeDescription.Entry.StDev }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.ShapeDescription.Entry.StDev createENDPOINTSTUDYRECORDAspectRatioShapeResultsAndDiscussionShapeDescriptionEntryStDev() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.ResultsAndDiscussion.ShapeDescription.Entry.StDev();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.DataGathering }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.DataGathering createENDPOINTSTUDYRECORDAspectRatioShapeMaterialsAndMethodsDataGathering() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.DataGathering();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDAspectRatioShapeMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.TestMaterials.ReferenceMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.TestMaterials.ReferenceMaterial.Entry createENDPOINTSTUDYRECORDAspectRatioShapeMaterialsAndMethodsTestMaterialsReferenceMaterialEntry() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.TestMaterials.ReferenceMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.Guideline.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.Guideline.Entry createENDPOINTSTUDYRECORDAspectRatioShapeMaterialsAndMethodsGuidelineEntry() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.MaterialsAndMethods.Guideline.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDAspectRatioShapeAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDAspectRatioShape.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDAspectRatioShape.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDAspectRatioShapeAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDAspectRatioShape.AdministrativeData.AttachedJustification.Entry();
    }

}
