//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.27 at 11:16:42 PM EET 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_phototransformationinsoil._5;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_phototransformationinsoil._5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataUsedForClassification_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-PhotoTransformationInSoil/5.0", "UsedForClassification");
    private final static QName _ENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataUsedForMSDS_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-PhotoTransformationInSoil/5.0", "UsedForMSDS");
    private final static QName _ENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataRobustStudy_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-PhotoTransformationInSoil/5.0", "RobustStudy");
    private final static QName _ENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesignDurationOfTestAtGivenTestConditionEntryMoisture_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-PhotoTransformationInSoil/5.0", "Moisture");
    private final static QName _ENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDegradationEntryKeyResult_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-PhotoTransformationInSoil/5.0", "KeyResult");
    private final static QName _ENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDegradationEntryStDev_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-PhotoTransformationInSoil/5.0", "StDev");
    private final static QName _ENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionQuantumYield_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-PhotoTransformationInSoil/5.0", "QuantumYield");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_phototransformationinsoil._5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil createENDPOINTSTUDYRECORDPhotoTransformationInSoil() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDPhotoTransformationInSoilApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.OverallRemarksAttachments createENDPOINTSTUDYRECORDPhotoTransformationInSoilOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDPhotoTransformationInSoilOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.IdentityTransformation }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.IdentityTransformation createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionIdentityTransformation() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.IdentityTransformation();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.IdentityTransformation.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.IdentityTransformation.Entry createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionIdentityTransformationEntry() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.IdentityTransformation.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.DissipationHalfLife }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.DissipationHalfLife createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDissipationHalfLife() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.DissipationHalfLife();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.DissipationHalfLife.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.DissipationHalfLife.Entry createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDissipationHalfLifeEntry() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.DissipationHalfLife.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDegradation() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDegradationEntry() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Spectrum }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Spectrum createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionSpectrum() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Spectrum();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Spectrum.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Spectrum.Entry createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionSpectrumEntry() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Spectrum.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesign() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesignDurationOfTestAtGivenTestCondition() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition.Entry createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesignDurationOfTestAtGivenTestConditionEntry() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.Guidelines }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.Guidelines createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsGuidelines() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.Guidelines();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.Guidelines.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.Guidelines.Entry createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsGuidelinesEntry() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.Guidelines.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.DataSource createENDPOINTSTUDYRECORDPhotoTransformationInSoilDataSource() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeData() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.AttachedJustification.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.DataProtection }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.DataProtection createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataDataProtection() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.DataProtection();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ApplicantSummaryAndConclusion.ValidityCriteriaFulfilled }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ApplicantSummaryAndConclusion.ValidityCriteriaFulfilled createENDPOINTSTUDYRECORDPhotoTransformationInSoilApplicantSummaryAndConclusionValidityCriteriaFulfilled() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ApplicantSummaryAndConclusion.ValidityCriteriaFulfilled();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDPhotoTransformationInSoilOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.TransformationProducts }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.TransformationProducts createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionTransformationProducts() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.TransformationProducts();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.IdentityTransformation.Entry.No }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.IdentityTransformation.Entry.No createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionIdentityTransformationEntryNo() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.IdentityTransformation.Entry.No();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.DissipationHalfLife.Entry.HalfLife }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.DissipationHalfLife.Entry.HalfLife createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDissipationHalfLifeEntryHalfLife() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.DissipationHalfLife.Entry.HalfLife();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.DissipationHalfLife.Entry.RemarksOnResults }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.DissipationHalfLife.Entry.RemarksOnResults createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDissipationHalfLifeEntryRemarksOnResults() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.DissipationHalfLife.Entry.RemarksOnResults();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry.DegradationPercent }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry.DegradationPercent createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDegradationEntryDegradationPercent() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry.DegradationPercent();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry.TimePoint }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry.TimePoint createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDegradationEntryTimePoint() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry.TimePoint();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry.RemarksOnResults }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry.RemarksOnResults createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDegradationEntryRemarksOnResults() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry.RemarksOnResults();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Spectrum.Entry.Parameter }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Spectrum.Entry.Parameter createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionSpectrumEntryParameter() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Spectrum.Entry.Parameter();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Spectrum.Entry.Value }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Spectrum.Entry.Value createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionSpectrumEntryValue() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Spectrum.Entry.Value();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.GLPComplianceStatement }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.GLPComplianceStatement createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsGLPComplianceStatement() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.GLPComplianceStatement();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.AnalyticalMonitoring }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.AnalyticalMonitoring createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesignAnalyticalMonitoring() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.AnalyticalMonitoring();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.AnalyticalMethod }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.AnalyticalMethod createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesignAnalyticalMethod() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.AnalyticalMethod();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.LightSource }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.LightSource createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesignLightSource() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.LightSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.LightSpectrumWavelengthInNm }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.LightSpectrumWavelengthInNm createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesignLightSpectrumWavelengthInNm() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.LightSpectrumWavelengthInNm();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.RelativeLightIntensity }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.RelativeLightIntensity createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesignRelativeLightIntensity() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.RelativeLightIntensity();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.ReferenceSubstance }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.ReferenceSubstance createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesignReferenceSubstance() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.ReferenceSubstance();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DarkControls }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DarkControls createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesignDarkControls() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DarkControls();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition.Entry.Duration }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition.Entry.Duration createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesignDurationOfTestAtGivenTestConditionEntryDuration() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition.Entry.Duration();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition.Entry.Temp }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition.Entry.Temp createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesignDurationOfTestAtGivenTestConditionEntryTemp() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition.Entry.Temp();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition.Entry.InitialConcMeasured }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition.Entry.InitialConcMeasured createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesignDurationOfTestAtGivenTestConditionEntryInitialConcMeasured() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition.Entry.InitialConcMeasured();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.TestMaterials.Radiolabelling }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.TestMaterials.Radiolabelling createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsTestMaterialsRadiolabelling() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.TestMaterials.Radiolabelling();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.Guidelines.Entry.Qualifier }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.Guidelines.Entry.Qualifier createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsGuidelinesEntryQualifier() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.Guidelines.Entry.Qualifier();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.Guidelines.Entry.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.Guidelines.Entry.Guideline createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsGuidelinesEntryGuideline() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.Guidelines.Entry.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.Guidelines.Entry.Deviation }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.Guidelines.Entry.Deviation createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsGuidelinesEntryDeviation() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.Guidelines.Entry.Deviation();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.DataSource.DataAccess }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.DataSource.DataAccess createENDPOINTSTUDYRECORDPhotoTransformationInSoilDataSourceDataAccess() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.DataSource.DataAccess();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.DataSource.DataProtectionClaimed }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.DataSource.DataProtectionClaimed createENDPOINTSTUDYRECORDPhotoTransformationInSoilDataSourceDataProtectionClaimed() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.DataSource.DataProtectionClaimed();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.Endpoint }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.Endpoint createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataEndpoint() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.Endpoint();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.StudyResultType }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.StudyResultType createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataStudyResultType() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.StudyResultType();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.PurposeFlag }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.PurposeFlag createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataPurposeFlag() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.PurposeFlag();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.Reliability }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.Reliability createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataReliability() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.Reliability();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.RationalReliability }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.RationalReliability createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataRationalReliability() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.RationalReliability();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.DataWaiving }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.DataWaiving createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataDataWaiving() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.DataWaiving();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.DataWaivingJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.DataWaivingJustification createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataDataWaivingJustification() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.DataWaivingJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.CrossReference.Entry.ReasonPurpose }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.CrossReference.Entry.ReasonPurpose createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataCrossReferenceEntryReasonPurpose() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.CrossReference.Entry.ReasonPurpose();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.AttachedJustification.Entry.ReasonPurpose }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.AttachedJustification.Entry.ReasonPurpose createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataAttachedJustificationEntryReasonPurpose() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.AttachedJustification.Entry.ReasonPurpose();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.DataProtection.Legislation }
     * 
     */
    public ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.DataProtection.Legislation createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataDataProtectionLegislation() {
        return new ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.DataProtection.Legislation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-PhotoTransformationInSoil/5.0", name = "UsedForClassification", scope = ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataUsedForClassification(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataUsedForClassification_QNAME, Boolean.class, ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-PhotoTransformationInSoil/5.0", name = "UsedForMSDS", scope = ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataUsedForMSDS(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataUsedForMSDS_QNAME, Boolean.class, ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-PhotoTransformationInSoil/5.0", name = "RobustStudy", scope = ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataRobustStudy(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDPhotoTransformationInSoilAdministrativeDataRobustStudy_QNAME, Boolean.class, ENDPOINTSTUDYRECORDPhotoTransformationInSoil.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-PhotoTransformationInSoil/5.0", name = "Moisture", scope = ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition.Entry.class)
    public JAXBElement<BigDecimal> createENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesignDurationOfTestAtGivenTestConditionEntryMoisture(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ENDPOINTSTUDYRECORDPhotoTransformationInSoilMaterialsAndMethodsStudyDesignDurationOfTestAtGivenTestConditionEntryMoisture_QNAME, BigDecimal.class, ENDPOINTSTUDYRECORDPhotoTransformationInSoil.MaterialsAndMethods.StudyDesign.DurationOfTestAtGivenTestCondition.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-PhotoTransformationInSoil/5.0", name = "KeyResult", scope = ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDegradationEntryKeyResult(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDegradationEntryKeyResult_QNAME, Boolean.class, ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-PhotoTransformationInSoil/5.0", name = "StDev", scope = ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry.class)
    public JAXBElement<BigDecimal> createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDegradationEntryStDev(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDegradationEntryStDev_QNAME, BigDecimal.class, ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.Degradation.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-PhotoTransformationInSoil/5.0", name = "KeyResult", scope = ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.DissipationHalfLife.Entry.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDissipationHalfLifeEntryKeyResult(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionDegradationEntryKeyResult_QNAME, Boolean.class, ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.DissipationHalfLife.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-PhotoTransformationInSoil/5.0", name = "QuantumYield", scope = ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.class)
    public JAXBElement<BigDecimal> createENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionQuantumYield(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ENDPOINTSTUDYRECORDPhotoTransformationInSoilResultsAndDiscussionQuantumYield_QNAME, BigDecimal.class, ENDPOINTSTUDYRECORDPhotoTransformationInSoil.ResultsAndDiscussion.class, value);
    }

}
