//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.18 at 12:12:22 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://echa.europa.eu/schemas/iuclid5/20130101", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.europa.echa.schemas.iuclid5._20130101.studyrecord.CATALYTIC_ACTIVITY_SECTION;
