//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.01 at 08:47:37 PM EEST 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_toxicityreproductionother._2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_toxicityreproductionother._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_toxicityreproductionother._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther createENDPOINTSTUDYRECORDToxicityReproductionOther() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.OverallRemarksAttachments createENDPOINTSTUDYRECORDToxicityReproductionOtherOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDToxicityReproductionOtherOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion createENDPOINTSTUDYRECORDToxicityReproductionOtherResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion.EffectLevels }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion.EffectLevels createENDPOINTSTUDYRECORDToxicityReproductionOtherResultsAndDiscussionEffectLevels() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion.EffectLevels();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion.EffectLevels.Efflevel }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion.EffectLevels.Efflevel createENDPOINTSTUDYRECORDToxicityReproductionOtherResultsAndDiscussionEffectLevelsEfflevel() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion.EffectLevels.Efflevel();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods createENDPOINTSTUDYRECORDToxicityReproductionOtherMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.AdministrationExposure }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.AdministrationExposure createENDPOINTSTUDYRECORDToxicityReproductionOtherMaterialsAndMethodsAdministrationExposure() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.AdministrationExposure();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.AdministrationExposure.DosesConcentrations }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.AdministrationExposure.DosesConcentrations createENDPOINTSTUDYRECORDToxicityReproductionOtherMaterialsAndMethodsAdministrationExposureDosesConcentrations() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.AdministrationExposure.DosesConcentrations();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.AdministrationExposure.DosesConcentrations.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.AdministrationExposure.DosesConcentrations.Entry createENDPOINTSTUDYRECORDToxicityReproductionOtherMaterialsAndMethodsAdministrationExposureDosesConcentrationsEntry() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.AdministrationExposure.DosesConcentrations.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.Guideline createENDPOINTSTUDYRECORDToxicityReproductionOtherMaterialsAndMethodsGuideline() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.AdministrativeData createENDPOINTSTUDYRECORDToxicityReproductionOtherAdministrativeData() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDToxicityReproductionOtherAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDToxicityReproductionOtherAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.DataSource createENDPOINTSTUDYRECORDToxicityReproductionOtherDataSource() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDToxicityReproductionOtherApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDToxicityReproductionOtherOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion.ObservedEffects }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion.ObservedEffects createENDPOINTSTUDYRECORDToxicityReproductionOtherResultsAndDiscussionObservedEffects() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion.ObservedEffects();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDToxicityReproductionOtherResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion.EffectLevels.Efflevel.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion.EffectLevels.Efflevel.Entry createENDPOINTSTUDYRECORDToxicityReproductionOtherResultsAndDiscussionEffectLevelsEfflevelEntry() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.ResultsAndDiscussion.EffectLevels.Efflevel.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDToxicityReproductionOtherMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.TestAnimals }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.TestAnimals createENDPOINTSTUDYRECORDToxicityReproductionOtherMaterialsAndMethodsTestAnimals() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.TestAnimals();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDToxicityReproductionOtherMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.AdministrationExposure.DosesConcentrations.Entry.DoseConc }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.AdministrationExposure.DosesConcentrations.Entry.DoseConc createENDPOINTSTUDYRECORDToxicityReproductionOtherMaterialsAndMethodsAdministrationExposureDosesConcentrationsEntryDoseConc() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.AdministrationExposure.DosesConcentrations.Entry.DoseConc();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.Guideline.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.Guideline.Entry createENDPOINTSTUDYRECORDToxicityReproductionOtherMaterialsAndMethodsGuidelineEntry() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.MaterialsAndMethods.Guideline.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDToxicityReproductionOtherAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDToxicityReproductionOther.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDToxicityReproductionOther.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDToxicityReproductionOtherAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDToxicityReproductionOther.AdministrativeData.AttachedJustification.Entry();
    }

}
