//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.01 at 08:47:26 PM EEST 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_specificsurfacearea._2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_specificsurfacearea._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_specificsurfacearea._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea createENDPOINTSTUDYRECORDSpecificSurfaceArea() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.OverallRemarksAttachments createENDPOINTSTUDYRECORDSpecificSurfaceAreaOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDSpecificSurfaceAreaOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.ResultsAndDiscussion createENDPOINTSTUDYRECORDSpecificSurfaceAreaResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.ResultsAndDiscussion.SpecificSurfaceArea }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.ResultsAndDiscussion.SpecificSurfaceArea createENDPOINTSTUDYRECORDSpecificSurfaceAreaResultsAndDiscussionSpecificSurfaceArea() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.ResultsAndDiscussion.SpecificSurfaceArea();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.ResultsAndDiscussion.SpecificSurfaceArea.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.ResultsAndDiscussion.SpecificSurfaceArea.Entry createENDPOINTSTUDYRECORDSpecificSurfaceAreaResultsAndDiscussionSpecificSurfaceAreaEntry() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.ResultsAndDiscussion.SpecificSurfaceArea.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods createENDPOINTSTUDYRECORDSpecificSurfaceAreaMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDSpecificSurfaceAreaMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.TestMaterials.ReferenceMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.TestMaterials.ReferenceMaterial createENDPOINTSTUDYRECORDSpecificSurfaceAreaMaterialsAndMethodsTestMaterialsReferenceMaterial() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.TestMaterials.ReferenceMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.Guideline createENDPOINTSTUDYRECORDSpecificSurfaceAreaMaterialsAndMethodsGuideline() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.AdministrativeData createENDPOINTSTUDYRECORDSpecificSurfaceAreaAdministrativeData() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDSpecificSurfaceAreaAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDSpecificSurfaceAreaAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.DataSource createENDPOINTSTUDYRECORDSpecificSurfaceAreaDataSource() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDSpecificSurfaceAreaApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDSpecificSurfaceAreaOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDSpecificSurfaceAreaResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.ResultsAndDiscussion.SpecificSurfaceArea.Entry.StDev }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.ResultsAndDiscussion.SpecificSurfaceArea.Entry.StDev createENDPOINTSTUDYRECORDSpecificSurfaceAreaResultsAndDiscussionSpecificSurfaceAreaEntryStDev() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.ResultsAndDiscussion.SpecificSurfaceArea.Entry.StDev();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.DataGathering }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.DataGathering createENDPOINTSTUDYRECORDSpecificSurfaceAreaMaterialsAndMethodsDataGathering() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.DataGathering();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDSpecificSurfaceAreaMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.TestMaterials.ReferenceMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.TestMaterials.ReferenceMaterial.Entry createENDPOINTSTUDYRECORDSpecificSurfaceAreaMaterialsAndMethodsTestMaterialsReferenceMaterialEntry() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.TestMaterials.ReferenceMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.Guideline.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.Guideline.Entry createENDPOINTSTUDYRECORDSpecificSurfaceAreaMaterialsAndMethodsGuidelineEntry() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.MaterialsAndMethods.Guideline.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDSpecificSurfaceAreaAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSpecificSurfaceArea.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSpecificSurfaceArea.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDSpecificSurfaceAreaAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDSpecificSurfaceArea.AdministrativeData.AttachedJustification.Entry();
    }

}
