//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.27 at 11:15:27 PM EET 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_granulometry._5;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_granulometry._5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ENDPOINTSTUDYRECORDGranulometryAdministrativeDataUsedForClassification_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-Granulometry/5.0", "UsedForClassification");
    private final static QName _ENDPOINTSTUDYRECORDGranulometryAdministrativeDataUsedForMSDS_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-Granulometry/5.0", "UsedForMSDS");
    private final static QName _ENDPOINTSTUDYRECORDGranulometryAdministrativeDataRobustStudy_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-Granulometry/5.0", "RobustStudy");
    private final static QName _ENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeEntryKeyResult_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-Granulometry/5.0", "KeyResult");
    private final static QName _ENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeEntryStDev_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-Granulometry/5.0", "StDev");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_granulometry._5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry createENDPOINTSTUDYRECORDGranulometry() {
        return new ENDPOINTSTUDYRECORDGranulometry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.OverallRemarksAttachments createENDPOINTSTUDYRECORDGranulometryOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDGranulometry.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDGranulometryOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDGranulometry.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeDistribution() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution.Entry createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeDistributionEntry() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSize() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeEntry() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods createENDPOINTSTUDYRECORDGranulometryMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.Guidelines }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.Guidelines createENDPOINTSTUDYRECORDGranulometryMaterialsAndMethodsGuidelines() {
        return new ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.Guidelines();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.Guidelines.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.Guidelines.Entry createENDPOINTSTUDYRECORDGranulometryMaterialsAndMethodsGuidelinesEntry() {
        return new ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.Guidelines.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.DataSource createENDPOINTSTUDYRECORDGranulometryDataSource() {
        return new ENDPOINTSTUDYRECORDGranulometry.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData createENDPOINTSTUDYRECORDGranulometryAdministrativeData() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDGranulometryAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDGranulometryAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDGranulometryAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDGranulometryAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.AttachedJustification.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.DataProtection }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.DataProtection createENDPOINTSTUDYRECORDGranulometryAdministrativeDataDataProtection() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.DataProtection();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDGranulometryApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDGranulometry.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDGranulometryOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDGranulometry.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.AerodynamicDiameter }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.AerodynamicDiameter createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionAerodynamicDiameter() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.AerodynamicDiameter();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.GeometricStandardDeviation }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.GeometricStandardDeviation createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionGeometricStandardDeviation() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.GeometricStandardDeviation();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.RemarksOnResults }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.RemarksOnResults createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionRemarksOnResults() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.RemarksOnResults();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution.Entry.No }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution.Entry.No createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeDistributionEntryNo() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution.Entry.No();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution.Entry.Size }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution.Entry.Size createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeDistributionEntrySize() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution.Entry.Size();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution.Entry.Distribution }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution.Entry.Distribution createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeDistributionEntryDistribution() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution.Entry.Distribution();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution.Entry.RemarksOnResults }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution.Entry.RemarksOnResults createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeDistributionEntryRemarksOnResults() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSizeDistribution.Entry.RemarksOnResults();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry.Percentile }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry.Percentile createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeEntryPercentile() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry.Percentile();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry.Mean }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry.Mean createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeEntryMean() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry.Mean();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry.RemarksOnResults }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry.RemarksOnResults createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeEntryRemarksOnResults() {
        return new ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry.RemarksOnResults();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.GLPComplianceStatement }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.GLPComplianceStatement createENDPOINTSTUDYRECORDGranulometryMaterialsAndMethodsGLPComplianceStatement() {
        return new ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.GLPComplianceStatement();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.OtherQualityAssurance }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.OtherQualityAssurance createENDPOINTSTUDYRECORDGranulometryMaterialsAndMethodsOtherQualityAssurance() {
        return new ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.OtherQualityAssurance();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.MethodType }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.MethodType createENDPOINTSTUDYRECORDGranulometryMaterialsAndMethodsMethodType() {
        return new ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.MethodType();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.TypeOfParticleTested }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.TypeOfParticleTested createENDPOINTSTUDYRECORDGranulometryMaterialsAndMethodsTypeOfParticleTested() {
        return new ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.TypeOfParticleTested();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.TypeOfDistribution }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.TypeOfDistribution createENDPOINTSTUDYRECORDGranulometryMaterialsAndMethodsTypeOfDistribution() {
        return new ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.TypeOfDistribution();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDGranulometryMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDGranulometryMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.Guidelines.Entry.Qualifier }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.Guidelines.Entry.Qualifier createENDPOINTSTUDYRECORDGranulometryMaterialsAndMethodsGuidelinesEntryQualifier() {
        return new ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.Guidelines.Entry.Qualifier();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.Guidelines.Entry.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.Guidelines.Entry.Guideline createENDPOINTSTUDYRECORDGranulometryMaterialsAndMethodsGuidelinesEntryGuideline() {
        return new ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.Guidelines.Entry.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.Guidelines.Entry.Deviation }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.Guidelines.Entry.Deviation createENDPOINTSTUDYRECORDGranulometryMaterialsAndMethodsGuidelinesEntryDeviation() {
        return new ENDPOINTSTUDYRECORDGranulometry.MaterialsAndMethods.Guidelines.Entry.Deviation();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.DataSource.DataAccess }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.DataSource.DataAccess createENDPOINTSTUDYRECORDGranulometryDataSourceDataAccess() {
        return new ENDPOINTSTUDYRECORDGranulometry.DataSource.DataAccess();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.DataSource.DataProtectionClaimed }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.DataSource.DataProtectionClaimed createENDPOINTSTUDYRECORDGranulometryDataSourceDataProtectionClaimed() {
        return new ENDPOINTSTUDYRECORDGranulometry.DataSource.DataProtectionClaimed();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.Endpoint }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.Endpoint createENDPOINTSTUDYRECORDGranulometryAdministrativeDataEndpoint() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.Endpoint();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.StudyResultType }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.StudyResultType createENDPOINTSTUDYRECORDGranulometryAdministrativeDataStudyResultType() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.StudyResultType();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.PurposeFlag }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.PurposeFlag createENDPOINTSTUDYRECORDGranulometryAdministrativeDataPurposeFlag() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.PurposeFlag();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.Reliability }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.Reliability createENDPOINTSTUDYRECORDGranulometryAdministrativeDataReliability() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.Reliability();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.RationalReliability }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.RationalReliability createENDPOINTSTUDYRECORDGranulometryAdministrativeDataRationalReliability() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.RationalReliability();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.DataWaiving }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.DataWaiving createENDPOINTSTUDYRECORDGranulometryAdministrativeDataDataWaiving() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.DataWaiving();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.DataWaivingJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.DataWaivingJustification createENDPOINTSTUDYRECORDGranulometryAdministrativeDataDataWaivingJustification() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.DataWaivingJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.CrossReference.Entry.ReasonPurpose }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.CrossReference.Entry.ReasonPurpose createENDPOINTSTUDYRECORDGranulometryAdministrativeDataCrossReferenceEntryReasonPurpose() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.CrossReference.Entry.ReasonPurpose();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.AttachedJustification.Entry.ReasonPurpose }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.AttachedJustification.Entry.ReasonPurpose createENDPOINTSTUDYRECORDGranulometryAdministrativeDataAttachedJustificationEntryReasonPurpose() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.AttachedJustification.Entry.ReasonPurpose();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.DataProtection.Legislation }
     * 
     */
    public ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.DataProtection.Legislation createENDPOINTSTUDYRECORDGranulometryAdministrativeDataDataProtectionLegislation() {
        return new ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.DataProtection.Legislation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-Granulometry/5.0", name = "UsedForClassification", scope = ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDGranulometryAdministrativeDataUsedForClassification(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDGranulometryAdministrativeDataUsedForClassification_QNAME, Boolean.class, ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-Granulometry/5.0", name = "UsedForMSDS", scope = ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDGranulometryAdministrativeDataUsedForMSDS(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDGranulometryAdministrativeDataUsedForMSDS_QNAME, Boolean.class, ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-Granulometry/5.0", name = "RobustStudy", scope = ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDGranulometryAdministrativeDataRobustStudy(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDGranulometryAdministrativeDataRobustStudy_QNAME, Boolean.class, ENDPOINTSTUDYRECORDGranulometry.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-Granulometry/5.0", name = "KeyResult", scope = ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeEntryKeyResult(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeEntryKeyResult_QNAME, Boolean.class, ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-Granulometry/5.0", name = "StDev", scope = ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry.class)
    public JAXBElement<BigDecimal> createENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeEntryStDev(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ENDPOINTSTUDYRECORDGranulometryResultsAndDiscussionParticleSizeEntryStDev_QNAME, BigDecimal.class, ENDPOINTSTUDYRECORDGranulometry.ResultsAndDiscussion.ParticleSize.Entry.class, value);
    }

}
