//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.01 at 08:46:05 PM EEST 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_biotransformationandkinetics._2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_biotransformationandkinetics._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_biotransformationandkinetics._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics createENDPOINTSTUDYRECORDBiotransformationAndKinetics() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.OverallRemarksAttachments createENDPOINTSTUDYRECORDBiotransformationAndKineticsOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDBiotransformationAndKineticsOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.ResultsAndDiscussion createENDPOINTSTUDYRECORDBiotransformationAndKineticsResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.ResultsAndDiscussion.IdentityTransformation }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.ResultsAndDiscussion.IdentityTransformation createENDPOINTSTUDYRECORDBiotransformationAndKineticsResultsAndDiscussionIdentityTransformation() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.ResultsAndDiscussion.IdentityTransformation();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.MaterialsAndMethods createENDPOINTSTUDYRECORDBiotransformationAndKineticsMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.MaterialsAndMethods.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.MaterialsAndMethods.Guideline createENDPOINTSTUDYRECORDBiotransformationAndKineticsMaterialsAndMethodsGuideline() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.MaterialsAndMethods.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.AdministrativeData createENDPOINTSTUDYRECORDBiotransformationAndKineticsAdministrativeData() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDBiotransformationAndKineticsAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDBiotransformationAndKineticsAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.DataSource createENDPOINTSTUDYRECORDBiotransformationAndKineticsDataSource() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDBiotransformationAndKineticsApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDBiotransformationAndKineticsOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDBiotransformationAndKineticsResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.ResultsAndDiscussion.IdentityTransformation.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.ResultsAndDiscussion.IdentityTransformation.Entry createENDPOINTSTUDYRECORDBiotransformationAndKineticsResultsAndDiscussionIdentityTransformationEntry() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.ResultsAndDiscussion.IdentityTransformation.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDBiotransformationAndKineticsMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDBiotransformationAndKineticsMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.MaterialsAndMethods.Guideline.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.MaterialsAndMethods.Guideline.Entry createENDPOINTSTUDYRECORDBiotransformationAndKineticsMaterialsAndMethodsGuidelineEntry() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.MaterialsAndMethods.Guideline.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDBiotransformationAndKineticsAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBiotransformationAndKinetics.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBiotransformationAndKinetics.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDBiotransformationAndKineticsAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDBiotransformationAndKinetics.AdministrativeData.AttachedJustification.Entry();
    }

}
