//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.26 at 10:45:33 AM EET 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_boilingpoint._5;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_boilingpoint._5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ENDPOINTSTUDYRECORDBoilingPointResultsAndDiscussionBoilingPointSetEntryKeyResult_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-BoilingPoint/5.0", "KeyResult");
    private final static QName _ENDPOINTSTUDYRECORDBoilingPointAdministrativeDataRobustStudy_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-BoilingPoint/5.0", "RobustStudy");
    private final static QName _ENDPOINTSTUDYRECORDBoilingPointAdministrativeDataUsedForClassification_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-BoilingPoint/5.0", "UsedForClassification");
    private final static QName _ENDPOINTSTUDYRECORDBoilingPointAdministrativeDataUsedForMSDS_QNAME = new QName("http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-BoilingPoint/5.0", "UsedForMSDS");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_boilingpoint._5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint createENDPOINTSTUDYRECORDBoilingPoint() {
        return new ENDPOINTSTUDYRECORDBoilingPoint();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.OverallRemarksAttachments createENDPOINTSTUDYRECORDBoilingPointOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDBoilingPointOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion createENDPOINTSTUDYRECORDBoilingPointResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet createENDPOINTSTUDYRECORDBoilingPointResultsAndDiscussionBoilingPointSet() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry createENDPOINTSTUDYRECORDBoilingPointResultsAndDiscussionBoilingPointSetEntry() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods createENDPOINTSTUDYRECORDBoilingPointMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.Guidelines }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.Guidelines createENDPOINTSTUDYRECORDBoilingPointMaterialsAndMethodsGuidelines() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.Guidelines();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.Guidelines.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.Guidelines.Entry createENDPOINTSTUDYRECORDBoilingPointMaterialsAndMethodsGuidelinesEntry() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.Guidelines.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.DataSource createENDPOINTSTUDYRECORDBoilingPointDataSource() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData createENDPOINTSTUDYRECORDBoilingPointAdministrativeData() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.AttachedJustification.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.DataProtection }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.DataProtection createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataDataProtection() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.DataProtection();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDBoilingPointApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDBoilingPointOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDBoilingPointResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.BoilingPoint }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.BoilingPoint createENDPOINTSTUDYRECORDBoilingPointResultsAndDiscussionBoilingPointSetEntryBoilingPoint() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.BoilingPoint();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.Pressure }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.Pressure createENDPOINTSTUDYRECORDBoilingPointResultsAndDiscussionBoilingPointSetEntryPressure() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.Pressure();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.Decomposition }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.Decomposition createENDPOINTSTUDYRECORDBoilingPointResultsAndDiscussionBoilingPointSetEntryDecomposition() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.Decomposition();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.DecompositionTemp }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.DecompositionTemp createENDPOINTSTUDYRECORDBoilingPointResultsAndDiscussionBoilingPointSetEntryDecompositionTemp() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.DecompositionTemp();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.RemarksOnResults }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.RemarksOnResults createENDPOINTSTUDYRECORDBoilingPointResultsAndDiscussionBoilingPointSetEntryRemarksOnResults() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.RemarksOnResults();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.GLPComplianceStatement }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.GLPComplianceStatement createENDPOINTSTUDYRECORDBoilingPointMaterialsAndMethodsGLPComplianceStatement() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.GLPComplianceStatement();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.OtherQualityAssurance }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.OtherQualityAssurance createENDPOINTSTUDYRECORDBoilingPointMaterialsAndMethodsOtherQualityAssurance() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.OtherQualityAssurance();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.MethodType }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.MethodType createENDPOINTSTUDYRECORDBoilingPointMaterialsAndMethodsMethodType() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.MethodType();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDBoilingPointMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDBoilingPointMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.Guidelines.Entry.Qualifier }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.Guidelines.Entry.Qualifier createENDPOINTSTUDYRECORDBoilingPointMaterialsAndMethodsGuidelinesEntryQualifier() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.Guidelines.Entry.Qualifier();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.Guidelines.Entry.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.Guidelines.Entry.Guideline createENDPOINTSTUDYRECORDBoilingPointMaterialsAndMethodsGuidelinesEntryGuideline() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.Guidelines.Entry.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.Guidelines.Entry.Deviation }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.Guidelines.Entry.Deviation createENDPOINTSTUDYRECORDBoilingPointMaterialsAndMethodsGuidelinesEntryDeviation() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.MaterialsAndMethods.Guidelines.Entry.Deviation();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.DataSource.DataAccess }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.DataSource.DataAccess createENDPOINTSTUDYRECORDBoilingPointDataSourceDataAccess() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.DataSource.DataAccess();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.DataSource.DataProtectionClaimed }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.DataSource.DataProtectionClaimed createENDPOINTSTUDYRECORDBoilingPointDataSourceDataProtectionClaimed() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.DataSource.DataProtectionClaimed();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.Endpoint }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.Endpoint createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataEndpoint() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.Endpoint();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.StudyResultType }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.StudyResultType createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataStudyResultType() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.StudyResultType();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.PurposeFlag }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.PurposeFlag createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataPurposeFlag() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.PurposeFlag();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.Reliability }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.Reliability createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataReliability() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.Reliability();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.RationalReliability }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.RationalReliability createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataRationalReliability() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.RationalReliability();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.DataWaiving }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.DataWaiving createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataDataWaiving() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.DataWaiving();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.DataWaivingJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.DataWaivingJustification createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataDataWaivingJustification() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.DataWaivingJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.CrossReference.Entry.ReasonPurpose }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.CrossReference.Entry.ReasonPurpose createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataCrossReferenceEntryReasonPurpose() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.CrossReference.Entry.ReasonPurpose();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.AttachedJustification.Entry.ReasonPurpose }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.AttachedJustification.Entry.ReasonPurpose createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataAttachedJustificationEntryReasonPurpose() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.AttachedJustification.Entry.ReasonPurpose();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.DataProtection.Legislation }
     * 
     */
    public ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.DataProtection.Legislation createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataDataProtectionLegislation() {
        return new ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.DataProtection.Legislation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-BoilingPoint/5.0", name = "KeyResult", scope = ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDBoilingPointResultsAndDiscussionBoilingPointSetEntryKeyResult(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDBoilingPointResultsAndDiscussionBoilingPointSetEntryKeyResult_QNAME, Boolean.class, ENDPOINTSTUDYRECORDBoilingPoint.ResultsAndDiscussion.BoilingPointSet.Entry.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-BoilingPoint/5.0", name = "RobustStudy", scope = ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataRobustStudy(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDBoilingPointAdministrativeDataRobustStudy_QNAME, Boolean.class, ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-BoilingPoint/5.0", name = "UsedForClassification", scope = ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataUsedForClassification(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDBoilingPointAdministrativeDataUsedForClassification_QNAME, Boolean.class, ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://iuclid6.echa.europa.eu/namespaces/ENDPOINT_STUDY_RECORD-BoilingPoint/5.0", name = "UsedForMSDS", scope = ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.class)
    public JAXBElement<Boolean> createENDPOINTSTUDYRECORDBoilingPointAdministrativeDataUsedForMSDS(Boolean value) {
        return new JAXBElement<Boolean>(_ENDPOINTSTUDYRECORDBoilingPointAdministrativeDataUsedForMSDS_QNAME, Boolean.class, ENDPOINTSTUDYRECORDBoilingPoint.AdministrativeData.class, value);
    }

}
