//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.01 at 08:47:12 PM EEST 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_sedimenttoxicity._2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_sedimenttoxicity._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_sedimenttoxicity._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity createENDPOINTSTUDYRECORDSedimentToxicity() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.OverallRemarksAttachments createENDPOINTSTUDYRECORDSedimentToxicityOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDSedimentToxicityOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.ResultsAndDiscussion createENDPOINTSTUDYRECORDSedimentToxicityResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.ResultsAndDiscussion.EffectConcentrations }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.ResultsAndDiscussion.EffectConcentrations createENDPOINTSTUDYRECORDSedimentToxicityResultsAndDiscussionEffectConcentrations() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.ResultsAndDiscussion.EffectConcentrations();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.ResultsAndDiscussion.EffectConcentrations.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.ResultsAndDiscussion.EffectConcentrations.Entry createENDPOINTSTUDYRECORDSedimentToxicityResultsAndDiscussionEffectConcentrationsEntry() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.ResultsAndDiscussion.EffectConcentrations.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods createENDPOINTSTUDYRECORDSedimentToxicityMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.StudyDesign }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.StudyDesign createENDPOINTSTUDYRECORDSedimentToxicityMaterialsAndMethodsStudyDesign() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.StudyDesign();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.StudyDesign.ExposureDuration }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.StudyDesign.ExposureDuration createENDPOINTSTUDYRECORDSedimentToxicityMaterialsAndMethodsStudyDesignExposureDuration() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.StudyDesign.ExposureDuration();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.StudyDesign.ExposureDuration.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.StudyDesign.ExposureDuration.Entry createENDPOINTSTUDYRECORDSedimentToxicityMaterialsAndMethodsStudyDesignExposureDurationEntry() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.StudyDesign.ExposureDuration.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.Guideline createENDPOINTSTUDYRECORDSedimentToxicityMaterialsAndMethodsGuideline() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.AdministrativeData createENDPOINTSTUDYRECORDSedimentToxicityAdministrativeData() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDSedimentToxicityAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDSedimentToxicityAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.DataSource createENDPOINTSTUDYRECORDSedimentToxicityDataSource() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDSedimentToxicityApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDSedimentToxicityOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDSedimentToxicityResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.ResultsAndDiscussion.EffectConcentrations.Entry.Duration }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.ResultsAndDiscussion.EffectConcentrations.Entry.Duration createENDPOINTSTUDYRECORDSedimentToxicityResultsAndDiscussionEffectConcentrationsEntryDuration() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.ResultsAndDiscussion.EffectConcentrations.Entry.Duration();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDSedimentToxicityMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.SamplingAndAnalysis }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.SamplingAndAnalysis createENDPOINTSTUDYRECORDSedimentToxicityMaterialsAndMethodsSamplingAndAnalysis() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.SamplingAndAnalysis();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.TestSubstrate }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.TestSubstrate createENDPOINTSTUDYRECORDSedimentToxicityMaterialsAndMethodsTestSubstrate() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.TestSubstrate();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.TestOrganisms }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.TestOrganisms createENDPOINTSTUDYRECORDSedimentToxicityMaterialsAndMethodsTestOrganisms() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.TestOrganisms();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.TestConditions }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.TestConditions createENDPOINTSTUDYRECORDSedimentToxicityMaterialsAndMethodsTestConditions() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.TestConditions();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDSedimentToxicityMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.StudyDesign.ExposureDuration.Entry.TotalExposureDuration }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.StudyDesign.ExposureDuration.Entry.TotalExposureDuration createENDPOINTSTUDYRECORDSedimentToxicityMaterialsAndMethodsStudyDesignExposureDurationEntryTotalExposureDuration() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.StudyDesign.ExposureDuration.Entry.TotalExposureDuration();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.Guideline.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.Guideline.Entry createENDPOINTSTUDYRECORDSedimentToxicityMaterialsAndMethodsGuidelineEntry() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.MaterialsAndMethods.Guideline.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDSedimentToxicityAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDSedimentToxicity.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDSedimentToxicity.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDSedimentToxicityAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDSedimentToxicity.AdministrativeData.AttachedJustification.Entry();
    }

}
