//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.01 at 08:47:30 PM EEST 
//


package eu.europa.echa.iuclid6.namespaces.endpoint_study_record_storagestability._2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.endpoint_study_record_storagestability._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.endpoint_study_record_storagestability._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability createENDPOINTSTUDYRECORDStorageStability() {
        return new ENDPOINTSTUDYRECORDStorageStability();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.OverallRemarksAttachments }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.OverallRemarksAttachments createENDPOINTSTUDYRECORDStorageStabilityOverallRemarksAttachments() {
        return new ENDPOINTSTUDYRECORDStorageStability.OverallRemarksAttachments();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.OverallRemarksAttachments.AttachedBackgroundMaterial }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.OverallRemarksAttachments.AttachedBackgroundMaterial createENDPOINTSTUDYRECORDStorageStabilityOverallRemarksAttachmentsAttachedBackgroundMaterial() {
        return new ENDPOINTSTUDYRECORDStorageStability.OverallRemarksAttachments.AttachedBackgroundMaterial();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.ResultsAndDiscussion }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.ResultsAndDiscussion createENDPOINTSTUDYRECORDStorageStabilityResultsAndDiscussion() {
        return new ENDPOINTSTUDYRECORDStorageStability.ResultsAndDiscussion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.ResultsAndDiscussion.IdentityTransformation }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.ResultsAndDiscussion.IdentityTransformation createENDPOINTSTUDYRECORDStorageStabilityResultsAndDiscussionIdentityTransformation() {
        return new ENDPOINTSTUDYRECORDStorageStability.ResultsAndDiscussion.IdentityTransformation();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods createENDPOINTSTUDYRECORDStorageStabilityMaterialsAndMethods() {
        return new ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods.Guideline }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods.Guideline createENDPOINTSTUDYRECORDStorageStabilityMaterialsAndMethodsGuideline() {
        return new ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods.Guideline();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.AdministrativeData }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.AdministrativeData createENDPOINTSTUDYRECORDStorageStabilityAdministrativeData() {
        return new ENDPOINTSTUDYRECORDStorageStability.AdministrativeData();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.AdministrativeData.CrossReference }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.AdministrativeData.CrossReference createENDPOINTSTUDYRECORDStorageStabilityAdministrativeDataCrossReference() {
        return new ENDPOINTSTUDYRECORDStorageStability.AdministrativeData.CrossReference();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.AdministrativeData.AttachedJustification }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.AdministrativeData.AttachedJustification createENDPOINTSTUDYRECORDStorageStabilityAdministrativeDataAttachedJustification() {
        return new ENDPOINTSTUDYRECORDStorageStability.AdministrativeData.AttachedJustification();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.DataSource }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.DataSource createENDPOINTSTUDYRECORDStorageStabilityDataSource() {
        return new ENDPOINTSTUDYRECORDStorageStability.DataSource();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.ApplicantSummaryAndConclusion }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.ApplicantSummaryAndConclusion createENDPOINTSTUDYRECORDStorageStabilityApplicantSummaryAndConclusion() {
        return new ENDPOINTSTUDYRECORDStorageStability.ApplicantSummaryAndConclusion();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry createENDPOINTSTUDYRECORDStorageStabilityOverallRemarksAttachmentsAttachedBackgroundMaterialEntry() {
        return new ENDPOINTSTUDYRECORDStorageStability.OverallRemarksAttachments.AttachedBackgroundMaterial.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables createENDPOINTSTUDYRECORDStorageStabilityResultsAndDiscussionAnyOtherInformationOnResultsInclTables() {
        return new ENDPOINTSTUDYRECORDStorageStability.ResultsAndDiscussion.AnyOtherInformationOnResultsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.ResultsAndDiscussion.IdentityTransformation.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.ResultsAndDiscussion.IdentityTransformation.Entry createENDPOINTSTUDYRECORDStorageStabilityResultsAndDiscussionIdentityTransformationEntry() {
        return new ENDPOINTSTUDYRECORDStorageStability.ResultsAndDiscussion.IdentityTransformation.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods.TestMaterials }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods.TestMaterials createENDPOINTSTUDYRECORDStorageStabilityMaterialsAndMethodsTestMaterials() {
        return new ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods.TestMaterials();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods.StudyDesign }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods.StudyDesign createENDPOINTSTUDYRECORDStorageStabilityMaterialsAndMethodsStudyDesign() {
        return new ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods.StudyDesign();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables createENDPOINTSTUDYRECORDStorageStabilityMaterialsAndMethodsAnyOtherInformationOnMaterialsAndMethodsInclTables() {
        return new ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods.AnyOtherInformationOnMaterialsAndMethodsInclTables();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods.Guideline.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods.Guideline.Entry createENDPOINTSTUDYRECORDStorageStabilityMaterialsAndMethodsGuidelineEntry() {
        return new ENDPOINTSTUDYRECORDStorageStability.MaterialsAndMethods.Guideline.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.AdministrativeData.CrossReference.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.AdministrativeData.CrossReference.Entry createENDPOINTSTUDYRECORDStorageStabilityAdministrativeDataCrossReferenceEntry() {
        return new ENDPOINTSTUDYRECORDStorageStability.AdministrativeData.CrossReference.Entry();
    }

    /**
     * Create an instance of {@link ENDPOINTSTUDYRECORDStorageStability.AdministrativeData.AttachedJustification.Entry }
     * 
     */
    public ENDPOINTSTUDYRECORDStorageStability.AdministrativeData.AttachedJustification.Entry createENDPOINTSTUDYRECORDStorageStabilityAdministrativeDataAttachedJustificationEntry() {
        return new ENDPOINTSTUDYRECORDStorageStability.AdministrativeData.AttachedJustification.Entry();
    }

}
