//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.25 at 10:16:49 AM EET 
//


package eu.europa.echa.iuclid6.namespaces.assessment_entity_groupofconstituentintheregisteredsubstance._5;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.echa.iuclid6.namespaces.assessment_entity_groupofconstituentintheregisteredsubstance._5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.echa.iuclid6.namespaces.assessment_entity_groupofconstituentintheregisteredsubstance._5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance }
     * 
     */
    public ASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance createASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance() {
        return new ASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance();
    }

    /**
     * Create an instance of {@link ASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance.EndpointSummariesList }
     * 
     */
    public ASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance.EndpointSummariesList createASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstanceEndpointSummariesList() {
        return new ASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance.EndpointSummariesList();
    }

    /**
     * Create an instance of {@link ASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance.AssessmentEntityConfidentialityClaim }
     * 
     */
    public ASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance.AssessmentEntityConfidentialityClaim createASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstanceAssessmentEntityConfidentialityClaim() {
        return new ASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance.AssessmentEntityConfidentialityClaim();
    }

    /**
     * Create an instance of {@link ASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance.EndpointSummariesList.Entry }
     * 
     */
    public ASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance.EndpointSummariesList.Entry createASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstanceEndpointSummariesListEntry() {
        return new ASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance.EndpointSummariesList.Entry();
    }

    /**
     * Create an instance of {@link ASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance.AssessmentEntityConfidentialityClaim.Legislation }
     * 
     */
    public ASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance.AssessmentEntityConfidentialityClaim.Legislation createASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstanceAssessmentEntityConfidentialityClaimLegislation() {
        return new ASSESSMENTENTITYGroupOfConstituentInTheRegisteredSubstance.AssessmentEntityConfidentialityClaim.Legislation();
    }

}
